### ISSUE TITLE
Stuck at the loading screen.

### ISSUE THREAD

**Issue by macke97531** [rebel1324/modernrp#6]
When im joining the server it stops at the  Sending player info or something no errors , any idea what it might be ?
Thanks for your time.

**Comment by rebel1324** [comment]
no server errors?

2015-01-11 0:18 GMT+09:00 macke97531 <notifications@github.com>:

**Comment by macke97531** [comment]
[ERROR] gamemodes/modernrp/entities/entities/nut_atm.lua:45: attempt to call field 'getMaterial' (a nil value)
  1. unknown - gamemodes/modernrp/entities/entities/nut_atm.lua:45


[ERROR] gamemodes/modernrp/entities/entities/nut_slotmachine.lua:60: attempt to call field 'getMaterial' (a nil value)
  1. unknown - gamemodes/modernrp/entities/entities/nut_slotmachine.lua:60

**Comment by rebel1324** [comment]
load it in dev branch.

2015-01-11 1:54 GMT+09:00 macke97531 <notifications@github.com>:

**Comment by macke97531** [comment]
And what does that mean exactly ?  ( sorry for being so retarded )

**Comment by macke97531** [comment]
Didnt help at all.
Fixed dev branch  + server dev branch

**Comment by macke97531** [comment]
I guess the gamemode will work when "gmod" fix a new update    ,  any idea when ?
